#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'

tput sgr0

echo "showing full verbose report"
kubectl logs -f job.batch/kube-bench -n default
echo

echo
echo -e "${ORANGE}'Summary' Report"
echo -e "${ORANGE}k logs -f job.batch/kube-bench -n default | grep -A 5 'Summary'"
kubectl logs -f job.batch/kube-bench -n default | grep -A 5 'Summary'
tput sgr0
echo
# == Summary ==
# 16 checks PASS
# 7 checks FAIL
# 2 checks WARN
# 0 checks INFO

echo -e "${RED}Show all 'FAIL'"
echo -e "${RED}kubectl logs -f job.batch/kube-bench -n default | grep 'FAIL'"
kubectl logs -f job.batch/kube-bench -n default | grep 'FAIL'
tput sgr0
echo
# [FAIL] 2.1.1 Ensure that the --allow-privileged argument is set to false (Scored)
# [FAIL] 2.1.5 Ensure that the --read-only-port argument is set to 0 (Scored)
# [FAIL] 2.1.7 Ensure that the --protect-kernel-defaults argument is set to true (Scored)
# [FAIL] 2.1.10 Ensure that the --event-qps argument is set to 0 (Scored)
# [FAIL] 2.1.11 Ensure that the --tls-cert-file and --tls-private-key-file arguments are set as appropriate (Scored)
# [FAIL] 2.2.5 Ensure that the proxy kubeconfig file permissions are set to 644 or more restrictive (Scored)
# [FAIL] 2.2.6 Ensure that the proxy kubeconfig file ownership is set to root:root (Scored)
# 7 checks FAIL
